// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using capsaicin_events_sharp;

#nullable disable

namespace capsaicin_events_sharp.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220430112223_Reactions")]
    partial class Reactions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("capsaicin_events_sharp.Entities.Attendee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("eventid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("eventid");

                    b.HasIndex("userid");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("creatorid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("creatorid");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.EventFile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("eventid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fileLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("eventid");

                    b.ToTable("EventFiles");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.Reaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("availibilityDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("eventid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("eventid");

                    b.HasIndex("userid");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.Attendee", b =>
                {
                    b.HasOne("capsaicin_events_sharp.Entities.Event", "event")
                        .WithMany()
                        .HasForeignKey("eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("capsaicin_events_sharp.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("event");

                    b.Navigation("user");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.Event", b =>
                {
                    b.HasOne("capsaicin_events_sharp.Entities.User", "creator")
                        .WithMany()
                        .HasForeignKey("creatorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.EventFile", b =>
                {
                    b.HasOne("capsaicin_events_sharp.Entities.Event", "event")
                        .WithMany()
                        .HasForeignKey("eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("event");
                });

            modelBuilder.Entity("capsaicin_events_sharp.Entities.Reaction", b =>
                {
                    b.HasOne("capsaicin_events_sharp.Entities.Event", "event")
                        .WithMany()
                        .HasForeignKey("eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("capsaicin_events_sharp.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("event");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
